### PR TITLE
Commited 

### PR DESCRIPTION
**Pull request by cscs2k**
findadentsit.ejs
index.ejs (lines 47-144)
index.js (lines 709-761)
vitaminform.ejs

### CODE REVIEW

**Comment by ottawa-ehospital** [comment]
Hello Team,

You have made changes to the existing files, please rectify that.

**Comment by ottawa-ehospital** [comment]
Please arrange a meeting.

**Comment by cscs2k** [comment]
Hi,

Will it be possible to have a meeting tomorrow?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ottawa-ehospital** [comment]
Please contact through email and we can arrange a meeting. 

Contact : Anas Javaid or Syed Asad Nadeem

**Pull request closed without merging**
